config/routes.rb
Rails.application.routes.draw do
  root :to => 'links#index'

  resources :links do
    resource :comments, only: [:new, :create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  validates :text, :presence => true
end

app/models/link.rb
class Link < ActiveRecord::Base
  before_save :strip_url
  validates :name, :presence => true
  validates :url, :presence => true
  has_many :comments

  private
  def strip_url
    self.url.sub!(/https\:\/\/www./, '') if self.url.include? "https://www."
    self.url.sub!(/http\:\/\/www./, '')  if self.url.include? "http://www."
    self.url.sub!(/www./, '')            if self.url.include? "www."
    return url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    if @comment.save
      redirect_to link_path(@link)
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:text)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.order("upvotes DESC")
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save()
      redirect_to links_path
    else
      render :new
    end
  end

  def update
    Link.find(params[:id]).increment!(:upvotes)
    redirect_to links_path
  end

  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
  end

  private

  def link_params
    params.require(:link).permit(:name, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_new.html.erb
<%= form_for [@link, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :new_comment %>
    <%= f.text_field :text, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slacker News ┐(´∀｀)┌</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <div class="container"> -->
  <%= yield %>
<!-- </div> -->
</body>
</html>

app/views/links/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">SLACKER NEWS</h1>
</div>

<div class="container">
  <ul class="list-unstyled list-group">
    <% @links.each do |link| %>
      <li class="list-group-item">
        <%= link_to '<span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>'.html_safe, link_path(link), id: link.id, method: "patch" %>

        <a href="http://www.<%=link.url%>"><%= link.name %></a>
        <p>
        <%= link.upvotes %> point | <%= link_to "comments", link_path(link), id: "comments-#{link.id}" %>
        </p>
      </li>
    <% end %>
  </ul>


  <p>
    <%= link_to "Add link", new_link_path, class: "btn btn-primary" %>
  </p>

</div>

app/views/links/new.html.erb
<h2>Add a link</h2>

<%= form_for @link do |f|%>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :url%>
    <%= f.text_field :url, class: "form-control"%>
  </div>
  <%= f.submit class: "btn btn-success"%>
<% end %>

app/views/links/show.html.erb
<h3><%= @link.name %></h3>

<%= render :partial => '/comments/new'%>

<ul class="list-unstyled list-group">
  <% @link.comments.each do |comment| %>
    <li class="list-group-item"><%=comment.text %></li>
  <% end %>
</ul>